"""Versioned interfaces shared by JUMP producers, executors, and readers."""

from .evidence import (
    RUN_RESULT_VERSION,
    SEALED_RESULT_VERSION,
    TASK_EVIDENCE_VERSION,
    EvidenceError,
    artifact_declaration,
    load_cached_result_envelope,
    load_task_evidence,
    load_verified_run_evidence,
    open_result_envelope,
    promote_task_artifacts,
    read_verified_artifact,
    seal_result_envelope,
    write_task_evidence,
)
from .latent import (
    LATENT_EVIDENCE_VERSION,
    TENSOR_PREIMAGE_VERSION,
    build_learned_latent_evidence,
    learned_decoder_identity,
    seal_learned_latent_result,
    tensor_bytes_sha256,
    validate_learned_latent_evidence,
    verify_decoded_image_bytes,
    verify_encoder_observation_bytes,
    verify_latent_tensor_bytes,
)

__all__ = [
    "RUN_RESULT_VERSION",
    "SEALED_RESULT_VERSION",
    "TASK_EVIDENCE_VERSION",
    "EvidenceError",
    "artifact_declaration",
    "load_cached_result_envelope",
    "load_task_evidence",
    "load_verified_run_evidence",
    "open_result_envelope",
    "promote_task_artifacts",
    "read_verified_artifact",
    "seal_result_envelope",
    "write_task_evidence",
    "LATENT_EVIDENCE_VERSION",
    "TENSOR_PREIMAGE_VERSION",
    "build_learned_latent_evidence",
    "learned_decoder_identity",
    "seal_learned_latent_result",
    "tensor_bytes_sha256",
    "validate_learned_latent_evidence",
    "verify_decoded_image_bytes",
    "verify_encoder_observation_bytes",
    "verify_latent_tensor_bytes",
]
